### ISSUE TITLE
UI/UX 

### ISSUE THREAD

**Issue by smaranjitghose** [techequilla/community_website_boilerplate#1]
Redesign the UI/UX of the website,

As of now, we require:

- Home Page
- Team Page
- Contact Us Page
- Blog Page
- Projects Page
- Announcements Page

**Comment by sakshi1499** [comment]
Please assign it to me or sonal sir

**Comment by sakshi1499** [comment]
![uxhome](https://user-images.githubusercontent.com/42520146/77252831-874df880-6c7c-11ea-81f1-4d52052cd532.jpeg)

**Comment by smaranjitghose** [comment]
Please do as I suggested on gitter

**Comment by sakshi1499** [comment]
Okay sir @smaranjitghose :)

**Comment by sakshi1499** [comment]
![image](https://user-images.githubusercontent.com/42520146/77255502-0dbf0600-6c8e-11ea-9691-6f288d232db6.png)

**Comment by sakshi1499** [comment]
![image](https://user-images.githubusercontent.com/42520146/77257009-b6be2e80-6c97-11ea-8886-a5d515ed63ce.png)

**Comment by sakshi1499** [comment]
![image](https://user-images.githubusercontent.com/42520146/77257420-2e8d5880-6c9a-11ea-91c1-8d18b0dfc578.png)

**Comment by sakshi1499** [comment]
![Web 1920 – 1](https://user-images.githubusercontent.com/42520146/77257671-d5262900-6c9b-11ea-933b-184c7dda0b0c.png)
![Web 1920 – 2](https://user-images.githubusercontent.com/42520146/77257672-d6efec80-6c9b-11ea-83b3-396b0746d788.png)
![Web 1920 – 3](https://user-images.githubusercontent.com/42520146/77257673-d8211980-6c9b-11ea-9ea2-1ea9be76bb9a.png)
![Web 1920 – 4](https://user-images.githubusercontent.com/42520146/77257675-d8b9b000-6c9b-11ea-8fbf-c8e41f3e842c.png)
![Web 1920 – 5](https://user-images.githubusercontent.com/42520146/77257676-d9524680-6c9b-11ea-9ef5-2f766fb4b90d.png)

**Comment by smaranjitghose** [comment]
Perfect. Give PRS, we shall review and get it integrated

**Comment by sakshi1499** [comment]
Yes, working on them😊

**Comment by shilpi1958** [comment]
![Community app home](https://user-images.githubusercontent.com/26502870/78264482-d7e90f80-7520-11ea-835e-440249dd797c.png)


Design for the home page of the community app.

1. the top bar has 5 tabs: Home, opportunities, saved posts/bookmark, blogs, our team. we can have contact details on the team page
2. left nav has details about you and what are you looking for.
3. We have posts in the middle section.
4. The rightmost section has notifications, with a cross bottom.

The projects refer to what the team is up to(am I right?). We can include this on our teams' page. Keeping the tabs limited to 5 and not increasing the cognitive load.

Feedback is welcome!
@smaranjitghose

**Comment by smaranjitghose** [comment]
As per the current workflow, the UI looks dope and this issue is closed until we require a major change in it.
Nice work Sonal and Sakshi to kickstart this development
