### ISSUE TITLE
Blog Page

### ISSUE THREAD

**Issue by smaranjitghose** [techequilla/community_website_boilerplate#17]
Create a Blog page that corresponds to the design of the website and integrate the blogs from:

 https://medium.com/techequilla

**Comment by anjalisoni3655** [comment]
Assign this to me !! Willing to work on it @smaranjitghose

**Comment by shilpi1958** [comment]
![BLOG](https://user-images.githubusercontent.com/26502870/78302886-55c90d00-7559-11ea-87d6-9c4e62cbcf76.png)
 
Corresponding to the design of home page in #1 
@smaranjitghose
