### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by smaranjitghose** [techequilla/community_website_boilerplate#18]
Create a Team Page that corresponds to the theme and design of the website and displays the following with some animations if possible:

- Organization Admin
whatever you wish to do with my profile 😅

- Project Maintainers

Cards showing names, profile pictures, social medium links and a small description

- Project Contributors:

Circular Icons of the Profiles of the Participants clicking on which a card pops up, showing their name, links to social profiles, and a small description/ or their contributions

Also, I would like to have an option that could easily fetch if someone's Pull request has been accepted for the group of projects under Techequilla and would dynamically update the number of contributors displayed on the same

**Comment by anjalisoni3655** [comment]
Assign this to me !! Willing to work on it @smaranjitghose

**Comment by anjalisoni3655** [comment]
@smaranjitghose Can you provide me the list of Project Maintainers and Project Contributors so that I can include it. Also from where do I need to collect the profile pictures?

**Comment by smaranjitghose** [comment]
Sure, I am the project Admin

The project mainters are:
@sukkritsharmaofficial
@anushbhatia
@ousnik
@swat1998

For project contributors just start with yours and your team mates and then we can add on the other participants accordingly

**Comment by smaranjitghose** [comment]
When you need the pictures, just send me a DM in gitter channel, I will provide you with a drive link

**Comment by anjalisoni3655** [comment]
I have to include just my teammate or the coaches as well in the project contributers??
@smaranjitghose

**Comment by gauravdas014** [comment]
@smaranjitghose can you tell me how to make the option that could easily fetch if someone's Pull request has been accepted for the group of projects under Techequilla. Tell me what I would have to do and I will do accordingly.

**Comment by anjalisoni3655** [comment]
can you please tell me how to make the option that could easily fetch if someone's Pull request has been accepted for the group of projects under Techequilla. Tell me what I will need to so I will do accordingly.
@smaranjitghose

**Comment by smaranjitghose** [comment]
Just the teammates

**Comment by smaranjitghose** [comment]
For now try using the script that shields.io uses for their badges or send some time on stackoverflow to figure it out

**Comment by anjalisoni3655** [comment]
I 'm  almost done with this task , was about to request a PR for the same  . @smaranjitghose  ,sir you should  have atleast informed me before unassigning this issue :(

**Comment by smaranjitghose** [comment]
I thought you were done with this issue after you gave the PR

**Comment by anjalisoni3655** [comment]
You had closed the  PR , so I was doing changes in it and sending another request with the suggested changes.

**Comment by smaranjitghose** [comment]
This will be continued with the new UI
