### ISSUE TITLE
Projects Page

### ISSUE THREAD

**Issue by smaranjitghose** [techequilla/community_website_boilerplate#19]
# Primary Task
Elegantly display the various projects on the TechEquilla Org done by all the members.
Name, Picture, Link to GitHub, A small description

# Associated Task
For this issue, once the basic page is up the participants can start contributing towards the other projects for the org that shall be displayed here. eg a VS CODE theme, a python package, a mass mailer, etc. You would be assigned those accordingly or feel free to approach me or the mentors for the same.

**Comment by anjalisoni3655** [comment]
Assign this to me !! Willing to work on it @smaranjitghose

**Comment by smaranjitghose** [comment]
Start with the primary task please

**Comment by anjalisoni3655** [comment]
@smaranjitghose from where do I get the list of projects to add . I need the necessary details to display to proceed further .

**Comment by smaranjitghose** [comment]
Makeup some demo content or see the existing repos on TechEquilla's Github org for some of them

**Comment by chhavi18387** [comment]
@smaranjitghose do we need to make a markdown file for this issue that contains all the information mentioned under Primary task ?

**Comment by anjalisoni3655** [comment]
@chhavi18387  I'm working on that issue .

**Comment by anjalisoni3655** [comment]
@smaranjitghose Please make two things clear: 
1) Are you asking to include the projects which are here:  https://github.com/Techequilla
2) Suppose some project is done my more than one person, in that case do we need to display the name , profile picture and github link of all of them?

**Comment by smaranjitghose** [comment]
Proceed as per my explanation in the Dms of Gitter channel

**Comment by smaranjitghose** [comment]
If you wish you can have a markdown file for this, but its not mandatory

**Comment by chhavi18387** [comment]
> @chhavi18387 I'm working on that issue .

Okay :)

**Comment by smaranjitghose** [comment]
This will be continued with the new UI
