### ISSUE TITLE
Achievements Page

### ISSUE THREAD

**Issue by smaranjitghose** [techequilla/community_website_boilerplate#20]
A feed showing the latest achievements of members from Hackathon wins to medals at coding competitions, giving everyone a platform to showcase and others a way to connect with people whose work they wish to emulate

Later on, have integration with LinkedIn,Twitter (and  Instagram if required) that reposts the same for the TechEquilla org pages. This is to be done while working with the Backend of the project

**Comment by anjalisoni3655** [comment]
Assign this to me !! Willing to work on it @smaranjitghose

**Comment by smaranjitghose** [comment]
@anjalisoni3655 I have assigned you three issues for now, once you are done with them, you can start on this as well..Cool?

**Comment by sakshi1499** [comment]
@smaranjitghose Assign it to me please :)

**Comment by smaranjitghose** [comment]
This will be continued with the new UI
