### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by smaranjitghose** [techequilla/community_website_boilerplate#21]
An overview of the org as well  as summarize all the sections of the website with our goals:

Check:  [GirlScript Chennai  Website](https://girlscriptchennai.netlify.com/) for reference

**Comment by anjalisoni3655** [comment]
Assign this to me !! Willing to work on it @smaranjitghose

**Comment by sonalsk** [comment]
Kindly assign is to me sir!
@smaranjitghose 
Team Femmetech!

**Comment by smaranjitghose** [comment]
This will be continued with the new UI
