### ISSUE TITLE
Blogs

### ISSUE THREAD

**Issue by anjalisoni3655** [techequilla/community_website_boilerplate#24]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
link to blog page is missing in the  home page,

**Describe alternatives you've considered**

**Add Screenshot**
Add relevant screenshot for suggestion

**Additional context**

**Comment by anjalisoni3655** [comment]
@smaranjitghose  please assign this to me .

**Comment by smaranjitghose** [comment]
Its already assigned to you. Please don't raise duplicate issues
