### ISSUE TITLE
Home page 

### ISSUE THREAD

**Issue by anjalisoni3655** [techequilla/community_website_boilerplate#25]
**Describe the bug**
In the footer of the homepage , the social media links are not working .

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anjalisoni3655** [comment]
@smaranjitghose please assign this to me.

**Comment by smaranjitghose** [comment]
Its already assigned to a team, if you want to make changes to it please coordinate with them on the design
