### ISSUE TITLE
Change in the font used

### ISSUE THREAD

**Issue by anushbhatia** [techequilla/community_website_boilerplate#34]
**Is your feature request related to a problem? Please describe.**
A new font to be used so that it looks more attractive.

**Describe the solution you'd like**
Drogowskaz
Futura
Selawik
Gotham
Montserrat
Source Sans Pro
Proximal nova
Poppins

**Comment by anjalisoni3655** [comment]
Please assign me this issue

**Comment by smaranjitghose** [comment]
This will be continued with the new UI
