### ISSUE TITLE
Bug in hamburger menu in phone view

### ISSUE THREAD

**Issue by anjalisoni3655** [techequilla/community_website_boilerplate#44]
Screenshot have been uploaded of current and what is expected
![Screenshot (67)](https://user-images.githubusercontent.com/51020896/78917199-31ff4d00-7aac-11ea-89ad-2422ec6346ba.png)
![Screenshot (68)](https://user-images.githubusercontent.com/51020896/78917207-33307a00-7aac-11ea-9435-7071d3c1c9a3.png)

**Comment by anjalisoni3655** [comment]
Please assign me this issue

**Comment by sonalsk** [comment]
Hey @anjalisoni3655 , the issue works fine in our machines and we tried it in various browsers as well. Could you reload and check if its working for you?

**Comment by anjalisoni3655** [comment]
Yah , it's working now .Sorry , some glitch may be 😅😅.
